server:
  port: 8082

spring:
  application:
    name: notification
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/schooldb
    #    username: postgres
    #    password: mysecretpassword
    username: 'vishal'
    url: jdbc:postgresql://localhost:5432/notification
    password: 'password'
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka